version: '3'
services:
  mongo:
    image: mongo
    restart: always
    networks:
      - angular-python
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH: false
    networks:
      - angular-python
    depends_on:
      - mongo

  api:
    restart: always
    image: python-app:0.2
    ports:
      - '5000:5000'
    volumes:
      -  ./containers/python:/app
    networks:
      - angular-python
  frontend:
    restart: always
    image: frontend:0.6
    ports:
      - '4200:4200'
    networks:
      - angular-python
networks:
  angular-python:
    driver: bridge
volumes:
  mongo_data: