apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-backend-deploy
spec:
  selector:
    matchLabels:
      name: myapp
      tier: backend
  template:
    metadata:
      labels:
        name: myapp
        tier: backend
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"