apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
spec:
  spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.9
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
