apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      name: nginx-2
      labels:
        name: myapp
    spec:
      containers:
      - name: nginx
        image: nginx