apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    name: myapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx