apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deploy
  labels:
    name: voting-app-deploy
    app: demo-voting-app
  spec:
    replicas: 1
    selector:
      name: voting-app-pod
      app: demo-voting-app
template:
  metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
  spec:
    containers:
    - name: voting-app
      image: ghcr.io/dockersamples/example-voting-app-vote
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
  

